package com.orion.portafolio2017.entity;
// Generated 29-10-2017 16:52:28 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estado generated by hbm2java
 */
@Entity
@Table(name = "estado")
public class Estado implements java.io.Serializable {

	@Id
	@Column(name = "id_estado", unique = true, nullable = false, precision = 8, scale = 0)
	private int idEstado;
	
	@Column(name = "nombre_estado", nullable = false, length = 50)
	private String nombreEstado;
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "estado")
	private Set<Permiso> permisos = new HashSet<Permiso>();

	public Estado() {
	}

	public Estado(int idEstado, String nombreEstado) {
		this.idEstado = idEstado;
		this.nombreEstado = nombreEstado;
	}

	
	public Estado(int idEstado, String nombreEstado, Set<Permiso> permisos) {
		super();
		this.idEstado = idEstado;
		this.nombreEstado = nombreEstado;
		this.permisos = permisos;
	}

	public int getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado(int idEstado) {
		this.idEstado = idEstado;
	}

	
	public String getNombreEstado() {
		return this.nombreEstado;
	}

	public void setNombreEstado(String nombreEstado) {
		this.nombreEstado = nombreEstado;
	}

	public Set<Permiso> getPermisos() {
		return permisos;
	}

	public void setPermisos(Set<Permiso> permisos) {
		this.permisos = permisos;
	}

	

}
