package com.orion.portafolio2017.entity;
// Generated 29-10-2017 16:52:28 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FuncionarioModel generated by hbm2java
 */
@Entity
@Table(name = "funcionario")
public class Funcionario implements java.io.Serializable {

	@Id
	@Column(name = "rut_funcionario", unique = true, nullable = false, length = 10)
	private String rutFuncionario;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "departamento_id_depto", nullable = false)
	private Departamento departamento;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cargo_id_cargo", nullable = false)
	private Cargo cargo;

	@Column(name = "primer_nombre", nullable = false, length = 20)
	private String primerNombre;

	@Column(name = "segundo_nombre", nullable = false, length = 20)
	private String segundoNombre;

	@Column(name = "primer_apellido", nullable = false, length = 20)
	private String primerApellido;

	@Column(name = "segundo_apellido", nullable = false, length = 20)
	private String segundoApellido;

	@Column(name = "telefono_funionario", nullable = false, precision = 10, scale = 0)
	private long telefonoFunionario;

	@Column(name = "sexo_funionario", nullable = false, length = 9)
	private String sexoFunionario;

	@Column(name = "correo_funcionario", nullable = false, length = 20)
	private String correoFuncionario;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "funcionario")
	private Set<Permiso> permisos = new HashSet<Permiso>();

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "funcionario")
	private Set<Usuario> usuarios = new HashSet<Usuario>();

	public Funcionario() {
	}

	public Funcionario(String rutFuncionario2) {
		// TODO Auto-generated constructor stub
	}

	public Funcionario(String rutFuncionario, Departamento departamento, Cargo cargo, String primerNombre,
			String segundoNombre, String primerApellido, String segundoApellido, long telefonoFunionario,
			String sexoFunionario, String correoFuncionario) {
		this.rutFuncionario = rutFuncionario;
		this.departamento = departamento;
		this.cargo = cargo;
		this.primerNombre = primerNombre;
		this.segundoNombre = segundoNombre;
		this.primerApellido = primerApellido;
		this.segundoApellido = segundoApellido;
		this.telefonoFunionario = telefonoFunionario;
		this.sexoFunionario = sexoFunionario;
		this.correoFuncionario = correoFuncionario;
	}

	public Funcionario(String rutFuncionario, Departamento departamento, Cargo cargo, String primerNombre,
			String segundoNombre, String primerApellido, String segundoApellido, long telefonoFunionario,
			String sexoFunionario, String correoFuncionario, Set<Permiso> permisos, Set<Usuario> usuarios) {
		super();
		this.rutFuncionario = rutFuncionario;
		this.departamento = departamento;
		this.cargo = cargo;
		this.primerNombre = primerNombre;
		this.segundoNombre = segundoNombre;
		this.primerApellido = primerApellido;
		this.segundoApellido = segundoApellido;
		this.telefonoFunionario = telefonoFunionario;
		this.sexoFunionario = sexoFunionario;
		this.correoFuncionario = correoFuncionario;
		this.permisos = permisos;
		this.usuarios = usuarios;
	}

	public String getRutFuncionario() {
		return this.rutFuncionario;
	}

	public void setRutFuncionario(String rutFuncionario) {
		this.rutFuncionario = rutFuncionario;
	}

	public Departamento getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(Departamento departamento) {
		this.departamento = departamento;
	}

	public Cargo getCargo() {
		return this.cargo;
	}

	public void setCargo(Cargo cargo) {
		this.cargo = cargo;
	}

	public String getPrimerNombre() {
		return this.primerNombre;
	}

	public void setPrimerNombre(String primerNombre) {
		this.primerNombre = primerNombre;
	}

	public String getSegundoNombre() {
		return this.segundoNombre;
	}

	public void setSegundoNombre(String segundoNombre) {
		this.segundoNombre = segundoNombre;
	}

	public String getPrimerApellido() {
		return this.primerApellido;
	}

	public void setPrimerApellido(String primerApellido) {
		this.primerApellido = primerApellido;
	}

	public String getSegundoApellido() {
		return this.segundoApellido;
	}

	public void setSegundoApellido(String segundoApellido) {
		this.segundoApellido = segundoApellido;
	}

	public long getTelefonoFunionario() {
		return this.telefonoFunionario;
	}

	public void setTelefonoFunionario(long telefonoFunionario) {
		this.telefonoFunionario = telefonoFunionario;
	}

	public String getSexoFunionario() {
		return this.sexoFunionario;
	}

	public void setSexoFunionario(String sexoFunionario) {
		this.sexoFunionario = sexoFunionario;
	}

	public String getCorreoFuncionario() {
		return this.correoFuncionario;
	}

	public void setCorreoFuncionario(String correoFuncionario) {
		this.correoFuncionario = correoFuncionario;
	}

	public Set<Permiso> getPermisos() {
		return permisos;
	}

	public void setPermisos(Set<Permiso> permisos) {
		this.permisos = permisos;
	}

	public Set<Usuario> getUsuarios() {
		return usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
