package com.orion.portafolio2017.entity;
// Generated 29-10-2017 16:52:28 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Perfil generated by hbm2java
 */
@Entity
@Table(name = "perfil")
public class Perfil implements java.io.Serializable {

	@Id
	@GeneratedValue
	@Column(name = "id_perfil", unique = true, nullable = false, precision = 8, scale = 0)
	private int idPerfil;
	
	@Column(name = "nombre_perfil", nullable = false, length = 30)
	private String nombrePerfil;
	
	@Column(name = "descripcion_perfil", nullable = false)
	private String descripcionPerfil;
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "perfil")
	private Set<Usuario> usuarios = new HashSet<Usuario>();

	public Perfil() {
	}

	public Perfil(int idPerfil, String nombrePerfil, String descripcionPerfil) {
		this.idPerfil = idPerfil;
		this.nombrePerfil = nombrePerfil;
		this.descripcionPerfil = descripcionPerfil;
	}



	public Perfil(int idPerfil, String nombrePerfil, String descripcionPerfil, Set<Usuario> usuarios) {
		super();
		this.idPerfil = idPerfil;
		this.nombrePerfil = nombrePerfil;
		this.descripcionPerfil = descripcionPerfil;
		this.usuarios = usuarios;
	}

	public int getIdPerfil() {
		return this.idPerfil;
	}

	public void setIdPerfil(int idPerfil) {
		this.idPerfil = idPerfil;
	}

	
	public String getNombrePerfil() {
		return this.nombrePerfil;
	}

	public void setNombrePerfil(String nombrePerfil) {
		this.nombrePerfil = nombrePerfil;
	}

	
	public String getDescripcionPerfil() {
		return this.descripcionPerfil;
	}

	public void setDescripcionPerfil(String descripcionPerfil) {
		this.descripcionPerfil = descripcionPerfil;
	}

	public Set<Usuario> getUsuarios() {
		return usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

	
	

}
