package com.orion.portafolio2017.entity;
// Generated 29-10-2017 16:52:28 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipo generated by hbm2java
 */
@Entity
@Table(name = "tipo")
public class Tipo implements java.io.Serializable {

	@Id
	@Column(name = "id_tipo", unique = true, nullable = false, precision = 8, scale = 0)
	private int idTipo;

	@Column(name = "nombre_tipo", nullable = false, length = 50)
	private String nombreTipo;

	@Column(name = "descripcion_tipo", nullable = false)
	private String descripcionTipo;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipo")
	private Set<Permiso> permisos = new HashSet<Permiso>();

	public Tipo() {
	}

	public Tipo(int idTipo, String nombreTipo, String descripcionTipo) {
		this.idTipo = idTipo;
		this.nombreTipo = nombreTipo;
		this.descripcionTipo = descripcionTipo;
	}



	public Tipo(int idTipo, String nombreTipo, String descripcionTipo, Set<Permiso> permisos) {
		super();
		this.idTipo = idTipo;
		this.nombreTipo = nombreTipo;
		this.descripcionTipo = descripcionTipo;
		this.permisos = permisos;
	}

	public int getIdTipo() {
		return this.idTipo;
	}

	public void setIdTipo(int idTipo) {
		this.idTipo = idTipo;
	}

	public String getNombreTipo() {
		return this.nombreTipo;
	}

	public void setNombreTipo(String nombreTipo) {
		this.nombreTipo = nombreTipo;
	}

	public String getDescripcionTipo() {
		return this.descripcionTipo;
	}

	public void setDescripcionTipo(String descripcionTipo) {
		this.descripcionTipo = descripcionTipo;
	}

	public Set<Permiso> getPermisos() {
		return permisos;
	}

	public void setPermisos(Set<Permiso> permisos) {
		this.permisos = permisos;
	}



}
